version: 3.8

services:
  postgres:
    image: postgres:15.1
    container_name: checkrun_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB = postgres
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = 12345678

  app:
    image: "chekrun"
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    container_name: check-runner-img
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB = postgres
      - SPRING_DATA_SOURCE_URL = jdbc:postgresql://localhost:5432/postgres
      - SPRING_DATA_SOURCE_USERNAME = postgres
      - SPRING_DATA_SOURCE_PASSWORD = 12345678
      - SPRING_JPA_HIBERNATE_DDL_AUTO= auto
      -
