version: 3.8

services:
  postgres:
    image: postgres:15.1
    container_name: checkrun_db
    environment:
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = 12345678
      - POSTGRES_DB = postgres

  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    container_name: check-runner-img
