version: '3.8'

services:
  app:
    image: 'chekrun:latest'
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: check-runner-img
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - POSTGRES_HOST = postgres
      - POSTGRES_PORT = 5432
      - POSTGRES_DB = postgres
      - SPRING_DATA_SOURCE_USERNAME = postgres
      - SPRING_DATA_SOURCE_PASSWORD = 12345678

  db:
    image: postgres:15.1
    restart: always
    container_name: 'db-img'
    ports:
      - '5432:5432'
    environment:
      - SPRING_DATA_SOURCE_URL = jdbc:postgresql://localhost:5432/postgres
      - POSTGRES_DB = postgres
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = 12345678
      - POSTGRES_HOST_AUTH_METHOD = trust
      - SPRING_JPA_HIBERNATE_DDL_AUTO= update
