DROP TABLE IF EXISTS discount_card;
DROP TABLE IF EXISTS products;
CREATE TABLE IF NOT EXISTS products
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title  VARCHAR(100),
    price FLOAT4,
    discount boolean,
    CONSTRAINT product_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS discount_card
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number_card BIGINT,
    discount_percent INT,
    CONSTRAINT discount_card_pkey PRIMARY KEY (id)
);
insert into discount_card (number_card, discount_percent) values (1234, 5);
insert into discount_card (number_card, discount_percent) values (9876, 8);
insert into discount_card (number_card, discount_percent) values (1724, 10);

insert into products(title, price, discount) values ('Potato', 5.43, false);
insert into products(title, price, discount) values ('Tomato', 6.36, false);
insert into products(title, price, discount) values ('Carrot', 3.49, true);
insert into products(title, price, discount) values ('Cabbage', 2.38, false);
insert into products(title, price, discount) values ('Cucumber', 1.48, true);
insert into products(title, price, discount) values ('Onion', 0.24, false);
insert into products(title, price, discount) values ('Garlic', 0.35, true);
insert into products(title, price, discount) values ('Pumpkin', 2.85, true);
insert into products(title, price, discount) values ('Courgette', 1.85, false);
insert into products(title, price, discount) values ('Spinach', 2.43, true);