DROP TABLE IF EXISTS products,discount_card;

CREATE TABLE IF NOT EXISTS products
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title  VARCHAR(100),
    price FLOAT4,
    discount boolean,
    CONSTRAINT product_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS discount_card
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number_card BIGINT,
    discount_percent INT,
    CONSTRAINT discount_card_pkey PRIMARY KEY (id)
);
